-- MySQL Script generated by MySQL Workbench
-- Fri Oct 13 18:51:47 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pcd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pcd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pcd` DEFAULT CHARACTER SET utf8 ;
USE `pcd` ;

-- -----------------------------------------------------
-- Table `pcd`.`classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`classe` (
  `classe_codigo` VARCHAR(9) NOT NULL,
  `classe_nome` VARCHAR(255) NOT NULL,
  `classe_ativa` INT NOT NULL,
  `classe_subordinacao` VARCHAR(45) NULL,
  PRIMARY KEY (`classe_codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcd`.`subclasse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`subclasse` (
  `subclasse_codigo` VARCHAR(9) NOT NULL,
  `subclasse_nome` VARCHAR(255) NOT NULL,
  `subclasse_ativa` INT NOT NULL,
  `classe_classe_codigo` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`subclasse_codigo`),
  INDEX `fk_subclasse_classe_idx` (`classe_classe_codigo` ASC),
  CONSTRAINT `fk_subclasse_classe`
    FOREIGN KEY (`classe_classe_codigo`)
    REFERENCES `pcd`.`classe` (`classe_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcd`.`grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`grupo` (
  `grupo_codigo` VARCHAR(9) NOT NULL,
  `grupo_nome` VARCHAR(255) NOT NULL,
  `grupo_ativo` INT NOT NULL,
  `subclasse_subclasse_codigo` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`grupo_codigo`),
  INDEX `fk_grupo_subclasse1_idx` (`subclasse_subclasse_codigo` ASC),
  CONSTRAINT `fk_grupo_subclasse1`
    FOREIGN KEY (`subclasse_subclasse_codigo`)
    REFERENCES `pcd`.`subclasse` (`subclasse_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcd`.`subgrupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`subgrupo` (
  `subgrupo_codigo` VARCHAR(9) NOT NULL,
  `subgrupo_nome` VARCHAR(255) NOT NULL,
  `subgrupo_ativo` INT NOT NULL,
  `grupo_grupo_codigo` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`subgrupo_codigo`),
  INDEX `fk_subgrupo_grupo1_idx` (`grupo_grupo_codigo` ASC),
  CONSTRAINT `fk_subgrupo_grupo1`
    FOREIGN KEY (`grupo_grupo_codigo`)
    REFERENCES `pcd`.`grupo` (`grupo_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcd`.`abertura_classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`abertura_classe` (
  `id_abertura_classe` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `responsavel` VARCHAR(45) NOT NULL,
  `classe_classe_codigo` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_abertura_classe`),
  CONSTRAINT `fk_abertura_classe_classe1`
    FOREIGN KEY (`classe_classe_codigo`)
    REFERENCES `pcd`.`classe` (`classe_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcd`.`desativacao_classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`desativacao_classe` (
  `id_desativacao_classe` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `responsavel` VARCHAR(45) NOT NULL,
  `classe_classe_codigo` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_desativacao_classe`),
  INDEX `fk_desativacao_classe_classe1_idx` (`classe_classe_codigo` ASC),
  CONSTRAINT `fk_desativacao_classe_classe1`
    FOREIGN KEY (`classe_classe_codigo`)
    REFERENCES `pcd`.`classe` (`classe_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcd`.`reativacao_classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`reativacao_classe` (
  `id_reativacao_classe` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `responsavel` VARCHAR(45) NOT NULL,
  `classe_classe_codigo` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_reativacao_classe`),
  INDEX `fk_reativacao_classe_classe1_idx` (`classe_classe_codigo` ASC),
  CONSTRAINT `fk_reativacao_classe_classe1`
    FOREIGN KEY (`classe_classe_codigo`)
    REFERENCES `pcd`.`classe` (`classe_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcd`.`mudanca_nome_classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`mudanca_nome_classe` (
  `id_mudancao_nome_classe` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `responsavel` VARCHAR(45) NOT NULL,
  `nome_anterior` VARCHAR(255) NOT NULL,
  `classe_classe_codigo` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_mudancao_nome_classe`),
  INDEX `fk_mudanca_nome_classe_classe1_idx` (`classe_classe_codigo` ASC),
  CONSTRAINT `fk_mudanca_nome_classe_classe1`
    FOREIGN KEY (`classe_classe_codigo`)
    REFERENCES `pcd`.`classe` (`classe_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcd`.`deslocamento_classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`deslocamento_classe` (
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `responsavel` VARCHAR(45) NOT NULL,
  `subordinacao_anterior` VARCHAR(45) NOT NULL,
  `id_deslocamento_classe` INT NOT NULL AUTO_INCREMENT,
  `classe_classe_codigo` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_deslocamento_classe`),
  INDEX `fk_deslocamento_classe_classe1_idx` (`classe_classe_codigo` ASC),
  CONSTRAINT `fk_deslocamento_classe_classe1`
    FOREIGN KEY (`classe_classe_codigo`)
    REFERENCES `pcd`.`classe` (`classe_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcd`.`extincao_classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`extincao_classe` (
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `responsavel` VARCHAR(45) NOT NULL,
  `classe_classe_codigo` VARCHAR(9) NOT NULL,
  `id_extincao_classe` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_extincao_classe`),
  CONSTRAINT `fk_extincao_classe_classe1`
    FOREIGN KEY (`classe_classe_codigo`)
    REFERENCES `pcd`.`classe` (`classe_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcd`.`registro_alteracao_classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`registro_alteracao_classe` (
  `id_registro_alteracao_classe` INT NOT NULL,
  `descricao` VARCHAR(955) NOT NULL,
  `prazo_anterior` DATE NOT NULL,
  `destinacao_anterior` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `responsavek` VARCHAR(45) NOT NULL,
  `classe_classe_codigo` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_registro_alteracao_classe`),
  INDEX `fk_registro_alteracao_classe_classe1_idx` (`classe_classe_codigo` ASC),
  CONSTRAINT `fk_registro_alteracao_classe_classe1`
    FOREIGN KEY (`classe_classe_codigo`)
    REFERENCES `pcd`.`classe` (`classe_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcd`.`registro_alteracao_subclasse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`registro_alteracao_subclasse` (
  `id_registro_alteracao_classe` INT NOT NULL,
  `descricao` VARCHAR(955) NOT NULL,
  `prazo_anterior` DATE NOT NULL,
  `destinacao_anterior` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `responsavek` VARCHAR(45) NOT NULL,
  `subclasse_subclasse_codigo` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_registro_alteracao_classe`),
  INDEX `fk_registro_alteracao_subclasse_subclasse1_idx` (`subclasse_subclasse_codigo` ASC),
  CONSTRAINT `fk_registro_alteracao_subclasse_subclasse1`
    FOREIGN KEY (`subclasse_subclasse_codigo`)
    REFERENCES `pcd`.`subclasse` (`subclasse_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcd`.`extincao_subclasse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`extincao_subclasse` (
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `responsavel` VARCHAR(45) NOT NULL,
  `subclasse_subclasse_codigo` VARCHAR(9) NOT NULL,
  `id_extincao_subclasse` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_extincao_subclasse`),
  CONSTRAINT `fk_extincao_subclasse_subclasse1`
    FOREIGN KEY (`subclasse_subclasse_codigo`)
    REFERENCES `pcd`.`subclasse` (`subclasse_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcd`.`deslocamento_subclasse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`deslocamento_subclasse` (
  `id_deslocamento_subclasse` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `responsavel` VARCHAR(45) NOT NULL,
  `subordinacao_anterior` VARCHAR(45) NOT NULL,
  `subclasse_subclasse_codigo` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_deslocamento_subclasse`),
  INDEX `fk_deslocamento_subclasse_subclasse1_idx` (`subclasse_subclasse_codigo` ASC),
  CONSTRAINT `fk_deslocamento_subclasse_subclasse1`
    FOREIGN KEY (`subclasse_subclasse_codigo`)
    REFERENCES `pcd`.`subclasse` (`subclasse_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcd`.`mudanca_nome_subclasse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`mudanca_nome_subclasse` (
  `id_mudanca_nome_subclasse` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `responsavel` VARCHAR(45) NOT NULL,
  `nome_anterior` VARCHAR(255) NOT NULL,
  `subclasse_subclasse_codigo` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_mudanca_nome_subclasse`),
  INDEX `fk_mudanca_nome_subclasse_subclasse1_idx` (`subclasse_subclasse_codigo` ASC),
  CONSTRAINT `fk_mudanca_nome_subclasse_subclasse1`
    FOREIGN KEY (`subclasse_subclasse_codigo`)
    REFERENCES `pcd`.`subclasse` (`subclasse_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcd`.`reativacao_subclasse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`reativacao_subclasse` (
  `id_reativacao_subclasse` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `responsavel` VARCHAR(45) NOT NULL,
  `subclasse_subclasse_codigo` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_reativacao_subclasse`),
  INDEX `fk_reativacao_subclasse_subclasse1_idx` (`subclasse_subclasse_codigo` ASC),
  CONSTRAINT `fk_reativacao_subclasse_subclasse1`
    FOREIGN KEY (`subclasse_subclasse_codigo`)
    REFERENCES `pcd`.`subclasse` (`subclasse_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcd`.`desativacao_subclasse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`desativacao_subclasse` (
  `id_desativacao_subclasse` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `responsavel` VARCHAR(45) NOT NULL,
  `subclasse_subclasse_codigo` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_desativacao_subclasse`),
  INDEX `fk_desativacao_subclasse_subclasse1_idx` (`subclasse_subclasse_codigo` ASC),
  CONSTRAINT `fk_desativacao_subclasse_subclasse1`
    FOREIGN KEY (`subclasse_subclasse_codigo`)
    REFERENCES `pcd`.`subclasse` (`subclasse_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcd`.`abertura_subclasse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`abertura_subclasse` (
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `responsavel` VARCHAR(45) NOT NULL,
  `subclasse_subclasse_codigo` VARCHAR(9) NOT NULL,
  `id_abertura_subclasse` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_abertura_subclasse`),
  CONSTRAINT `fk_abertura_subclasse_subclasse1`
    FOREIGN KEY (`subclasse_subclasse_codigo`)
    REFERENCES `pcd`.`subclasse` (`subclasse_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcd`.`registro_alteracao_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`registro_alteracao_grupo` (
  `id_registro_alteracao_grupo` INT NOT NULL,
  `descricao` VARCHAR(955) NOT NULL,
  `prazo_anterior` DATE NOT NULL,
  `destinacao_anterior` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `responsavek` VARCHAR(45) NOT NULL,
  `grupo_grupo_codigo` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_registro_alteracao_grupo`),
  INDEX `fk_registro_alteracao_grupo_grupo1_idx` (`grupo_grupo_codigo` ASC),
  CONSTRAINT `fk_registro_alteracao_grupo_grupo1`
    FOREIGN KEY (`grupo_grupo_codigo`)
    REFERENCES `pcd`.`grupo` (`grupo_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcd`.`extincao_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`extincao_grupo` (
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `responsavel` VARCHAR(45) NOT NULL,
  `grupo_grupo_codigo` VARCHAR(9) NOT NULL,
  `id_extincao_grupo` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_extincao_grupo`),
  CONSTRAINT `fk_extincao_grupo_grupo1`
    FOREIGN KEY (`grupo_grupo_codigo`)
    REFERENCES `pcd`.`grupo` (`grupo_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcd`.`deslocamento_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`deslocamento_grupo` (
  `id_deslocamento_grupo` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `responsavel` VARCHAR(45) NOT NULL,
  `subordinacao_anterior` VARCHAR(45) NOT NULL,
  `grupo_grupo_codigo` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_deslocamento_grupo`),
  INDEX `fk_deslocamento_grupo_grupo1_idx` (`grupo_grupo_codigo` ASC),
  CONSTRAINT `fk_deslocamento_grupo_grupo1`
    FOREIGN KEY (`grupo_grupo_codigo`)
    REFERENCES `pcd`.`grupo` (`grupo_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcd`.`mudanca_nome_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`mudanca_nome_grupo` (
  `id_mudanca_nome_grupo` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `responsavel` VARCHAR(45) NOT NULL,
  `nome_anterior` VARCHAR(255) NOT NULL,
  `grupo_grupo_codigo` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_mudanca_nome_grupo`),
  INDEX `fk_mudanca_nome_grupo_grupo1_idx` (`grupo_grupo_codigo` ASC),
  CONSTRAINT `fk_mudanca_nome_grupo_grupo1`
    FOREIGN KEY (`grupo_grupo_codigo`)
    REFERENCES `pcd`.`grupo` (`grupo_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcd`.`reativacao_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`reativacao_grupo` (
  `id_reativacao_grupo` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `responsavel` VARCHAR(45) NOT NULL,
  `grupo_grupo_codigo` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_reativacao_grupo`),
  INDEX `fk_reativacao_grupo_grupo1_idx` (`grupo_grupo_codigo` ASC),
  CONSTRAINT `fk_reativacao_grupo_grupo1`
    FOREIGN KEY (`grupo_grupo_codigo`)
    REFERENCES `pcd`.`grupo` (`grupo_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcd`.`desativacao_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`desativacao_grupo` (
  `id_desativacao_grupo` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `responsavel` VARCHAR(45) NOT NULL,
  `grupo_grupo_codigo` VARCHAR(9) NOT NULL,
  INDEX `fk_desativacao_grupo_grupo1_idx` (`grupo_grupo_codigo` ASC),
  PRIMARY KEY (`id_desativacao_grupo`),
  CONSTRAINT `fk_desativacao_grupo_grupo1`
    FOREIGN KEY (`grupo_grupo_codigo`)
    REFERENCES `pcd`.`grupo` (`grupo_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcd`.`abertura_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`abertura_grupo` (
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `responsavel` VARCHAR(45) NOT NULL,
  `grupo_grupo_codigo` VARCHAR(9) NOT NULL,
  `id_abertura_grupo` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_abertura_grupo`),
  CONSTRAINT `fk_abertura_grupo_grupo1`
    FOREIGN KEY (`grupo_grupo_codigo`)
    REFERENCES `pcd`.`grupo` (`grupo_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcd`.`registro_alteracao_subgrupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`registro_alteracao_subgrupo` (
  `id_registro_alteracao_subgrupo` INT NOT NULL,
  `descricao` VARCHAR(955) NOT NULL,
  `prazo_anterior` DATE NOT NULL,
  `destinacao_anterior` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `responsavek` VARCHAR(45) NOT NULL,
  `grupo_grupo_codigo` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_registro_alteracao_subgrupo`),
  INDEX `fk_registro_alteracao_subgrupo_subgrupo1_idx` (`grupo_grupo_codigo` ASC),
  CONSTRAINT `fk_registro_alteracao_subgrupo_subgrupo1`
    FOREIGN KEY (`grupo_grupo_codigo`)
    REFERENCES `pcd`.`subgrupo` (`subgrupo_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcd`.`extincao_subgrupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`extincao_subgrupo` (
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `responsavel` VARCHAR(45) NOT NULL,
  `subgrupo_subgrupo_codigo` VARCHAR(9) NOT NULL,
  `id_extincao_subgrupo` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_extincao_subgrupo`),
  CONSTRAINT `fk_extincao_subgrupo_subgrupo1`
    FOREIGN KEY (`subgrupo_subgrupo_codigo`)
    REFERENCES `pcd`.`subgrupo` (`subgrupo_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcd`.`deslocamento_subgrupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`deslocamento_subgrupo` (
  `id_deslocamento_subgrupo` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `responsavel` VARCHAR(45) NOT NULL,
  `subordinacao_anterior` VARCHAR(45) NOT NULL,
  `subgrupo_subgrupo_codigo` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_deslocamento_subgrupo`),
  INDEX `fk_deslocamento_subgrupo_subgrupo1_idx` (`subgrupo_subgrupo_codigo` ASC),
  CONSTRAINT `fk_deslocamento_subgrupo_subgrupo1`
    FOREIGN KEY (`subgrupo_subgrupo_codigo`)
    REFERENCES `pcd`.`subgrupo` (`subgrupo_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcd`.`mudanca_nome_subgrupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`mudanca_nome_subgrupo` (
  `id_mudanca_nome_subgrupo` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `responsavel` VARCHAR(45) NOT NULL,
  `nome_anterior` VARCHAR(255) NOT NULL,
  `subgrupo_subgrupo_codigo` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_mudanca_nome_subgrupo`),
  INDEX `fk_mudanca_nome_subgrupo_subgrupo1_idx` (`subgrupo_subgrupo_codigo` ASC),
  CONSTRAINT `fk_mudanca_nome_subgrupo_subgrupo1`
    FOREIGN KEY (`subgrupo_subgrupo_codigo`)
    REFERENCES `pcd`.`subgrupo` (`subgrupo_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcd`.`reativacao_subgrupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`reativacao_subgrupo` (
  `id_reativacao_subgrupo` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `responsavel` VARCHAR(45) NOT NULL,
  `subgrupo_subgrupo_codigo` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_reativacao_subgrupo`),
  INDEX `fk_reativacao_subgrupo_subgrupo1_idx` (`subgrupo_subgrupo_codigo` ASC),
  CONSTRAINT `fk_reativacao_subgrupo_subgrupo1`
    FOREIGN KEY (`subgrupo_subgrupo_codigo`)
    REFERENCES `pcd`.`subgrupo` (`subgrupo_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcd`.`desativacao_subgrupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`desativacao_subgrupo` (
  `id_desativacao_subgrupo` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `responsavel` VARCHAR(45) NOT NULL,
  `subgrupo_subgrupo_codigo` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id_desativacao_subgrupo`),
  INDEX `fk_desativacao_subgrupo_subgrupo1_idx` (`subgrupo_subgrupo_codigo` ASC),
  CONSTRAINT `fk_desativacao_subgrupo_subgrupo1`
    FOREIGN KEY (`subgrupo_subgrupo_codigo`)
    REFERENCES `pcd`.`subgrupo` (`subgrupo_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcd`.`abertura_subgrupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`abertura_subgrupo` (
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `responsavel` VARCHAR(45) NOT NULL,
  `subgrupo_subgrupo_codigo` VARCHAR(9) NOT NULL,
  `id_abertura_subgrupo` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_abertura_subgrupo`),
  CONSTRAINT `fk_abertura_subgrupo_subgrupo1`
    FOREIGN KEY (`subgrupo_subgrupo_codigo`)
    REFERENCES `pcd`.`subgrupo` (`subgrupo_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pcd`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pcd`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `userLogin` VARCHAR(45) NOT NULL,
  `userPass` VARCHAR(512) NOT NULL,
  `userType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
